name: C/C++ CI

on:
  push:
    branches: [ slmk ]
  pull_request:
    branches: [ slmk ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: toolchain
      run: git clone --depth=1 https://github.com/arter97/arm64-gcc ~/tc/
    - name: configure
      run: make O=out ARCH=arm64 xandroid_defconfig
    - name: make
      run: make O=out ARCH=arm64 CROSS_COMPILE=~/tc/bin/aarch64-elf- -j$(nproc --all)
    - name: bootimage
      run: ./tools/mkbootimg --kernel out/arch/arm64/boot/Image.gz --base 0x00400000 --cmdline "loglevel=4 coherent_pool=512K page_tracker=on slub_min_objects=12 unmovable_isolate1=2:192M,3:224M,4:256M printktimer=0xfff0a000,0x534,0x538 androidboot.selinux=enforcing buildvariant=user" --tags_offset 0x07A00000 --kernel_offset 0x00080000 --ramdisk_offset 0x10000000 --os_version 9 --os_patch_level 2020-06-01  --output xandroid-kramel-$(date +%d%m%y-%S%M).img
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
         tag_name: ${{ github.ref }}
         release_name: Release ${{ github.ref }}
         draft: true
         prerelease: true
