name: Upstream Kernel

on:  
  push:
  pull_request:
  schedule:
    - cron: '45 9 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install git
    - name: Rebase
      run: |
        git config --global user.name "xandroid64"
        git config --global user.email "xandroid64@users.noreply.github.com"
        git clone https://"${GITHUB_USER}":"${GITHUB_TOKEN}"@github.com/xandroid64/bnd.git
        cd bnd
        git checkout -b upstream
        bash linux-stable.sh -m
        git push origin upstream
      env:
        GITHUB_EMAIL: ${{ secrets.EMAIL }}
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        GITHUB_USER: ${{ secrets.USERNAME }}    
